print("TEST\tSCORE\tPROGRAM")
print()
print("hello... uh... put your scores in...")
print("=====================")
score1 = input("Test Score Uno:\t")
score2 = input("Test Score Dos:\t")
score3 = input("Test Score Tres:\t")
print("=====================")
#calcutations
superscore = round(float(score1) + float(score2) + float(score3)
avgscore = round(superscore / 3)
input("um one second")
input("IM NOT READY")
print("ok fine lets go")
print("uh... SCORES: ",score1,score2,score3, "... heh")
print("combined score is um...")
print("uh...")
print("...")
print("COMBINED SCORE:",superscore)
print("and finally... ... ...")
print("AVERAGE SCORE:",avgscore)
